### ISSUE TITLE
Data driven tests

### ISSUE THREAD

**Issue by VarIr** [OFAI/hub-toolbox-python3#1]
Might consider using ddt for testing HubnessAnalysis (and possibly others), 
see https://technomilk.wordpress.com/2012/02/12/multiplying-python-unit-test-cases-with-different-sets-of-data/

**Comment by f0k** [comment]
Also have a look at py.test -- it supports this via a decorator ([`@parameterize`](http://doc.pytest.org/en/latest/parametrize.html#parametrize-basics)).

**Comment by VarIr** [comment]
Thanks, looks nice!
