### ISSUE TITLE
please add GPU support

### ISSUE THREAD

**Issue by Pzoom522** [OFAI/hub-toolbox-python3#7]
Hi, thanks for building this wonderful repo! It would be great if CUDA support could be added to accelerate the computation of k-occurrence.

**Comment by VarIr** [comment]
Thanks for your feedback. Unfortunately, GPU support is out of scope at the moment, as this would require porting all numpy code to torch, or similar. While in principle possible, we shifted our focus to the development of [scikit-hubness](https://github.com/VarIr/scikit-hubness), which has a much cleaner codebase, interfaces nicely with scikit-learn, and provides approximate NN search, which can also speed up k-occurrence.
