### ISSUE TITLE
AttributeError: module 'hub_toolbox' has no attribute 'IO'

### ISSUE THREAD

**Issue by eduamf** [OFAI/hub-toolbox-python3#8]
I received the following message: AttributeError: module 'hub_toolbox' has no attribute 'IO'.

I`m using Windows 10 and Python 3.7. The package was installed without error using pip.

**Comment by eduamf** [comment]
I follow the code and the reference is wrong. It is `hub_toolbox.io.load_dexter()`, lowercase. In fact, there are others modules with lowercase names.

I had to install nmslib by source:
`pip install --no-binary :all: nmslib`

**Comment by VarIr** [comment]
Which version have you got? `hub_toolbox.__version__`
Windows is not officially supported, and I cannot test on a Windows machine.
You could try to clone the repository and install the package from there instead of PyPI.
``` bash
git clone https://github.com/OFAI/hub-toolbox-python3.git
cd hub-toolbox-python3
pip install .
```

**Comment by eduamf** [comment]
The version is 2.5.2.

And I did this:
```
git clone https://github.com/OFAI/hub-toolbox-python3.git
cd hub-toolbox-python3
pip install --no-binary :all: nmslib
python setup.py build
python setup.py install 
```
Till now, the only error is:
```
...
D_mp = hub_toolbox.MutualProximity.mutual_proximity_empiric(D=D, metric='distance')

```
**AttributeError: module 'hub_toolbox' has no attribute 'MutualProximity'**

I didn`t find the any module named **MutualProximity**.

**Comment by eduamf** [comment]
I found a code to MatLab with a similar name:
https://github.com/OFAI/hub-toolbox-matlab/blob/master/mutual_proximity.m

**Comment by VarIr** [comment]
I see, we never updated the usage example in the readme when the package was restructured (for lowercase module names etc). Thanks for bringing that to my attention.
In case of MP, the module was also renamed to `global_scaling.py`. So please try 
`D_mp = hub_toolbox.global_scaling.mutual_proximity_empiric(D=D, metric='distance')`

We don't actively develop both hub-toolbox-python3 or hub-toolbox-matlab anymore.
The [`scikit-hubness`](https://github.com/VarIr/scikit-hubness/) replaces them.

**Comment by eduamf** [comment]
Thank you.
